services:
  postgres-db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: product_service
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      retries: 5
      interval: 10s
      timeout: 5s
      start_period: 10s
      start_interval: 10s
    ports:
      - "${DB_PORT:-5432}:5432"

  kafka-service:
    image: apache/kafka
    container_name: kafka
    ports:
      - "9092:9092"

  redis-service:
    image: redis
    ports:
      - "${REDIS_PORT:-6379}:6379"


  product-service:
    build: ./product-service
    environment:
      DB_HOST: ${DB_HOST:-postgres-db}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "8081:8081"
    depends_on:
      postgres-db:
          condition: service_healthy

  cart-service:
    build: ./cart-service
    ports:
      - "8082:8082"
    environment:
      DB_HOST: ${DB_HOST:-postgres-db}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      PRODUCT_SERVICE_BASE_URL: http://product-service:8081/product
    depends_on:
      postgres-db:
        condition: service_healthy
      product-service:
        condition: service_started

  user-service:
    build: user-service
    ports:
      - "8080:8080"
    environment:
      DB_HOST: ${DB_HOST:-postgres-db}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      REDIS_HOST: ${REDIS_HOST:-redis-service}
      REDIS_PORT: ${REDIS_PORT:-6379}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      postgres-db:
          condition: service_healthy
      redis-service:
        condition: service_started

volumes:
  postgres-data:
