spring.application.name=user-service

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/user_service
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA (IMPORTANT)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

#JWT
jwt.secret = jm9iyTwMsq7HGf4OCKhy1DFbHk0d499Q3vZH7Kg546Q=
jwt.expiration = 100000

spring.cache.type=simple