spring.application.name=user-service

# Database
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/user_service
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA (IMPORTANT)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

#JWT
jwt.secret = jm9iyTwMsq7HGf4OCKhy1DFbHk0d499Q3vZH7Kg546Q=
jwt.expiration = 600000

#  Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

spring.cache.type=redis
spring.cache.redis.time-to-live=600000
