server:
  port: 8081

spring:
  application:
    name: product-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/product_service?options=-c%20TimeZone=Asia/Kolkata
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  flyway:
    enabled: true
    locations: classpath:db/migration

