server:
  port: 8081

spring:
  application:
    name: product-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:postgresql://localhost:5432/product_service
    username: postgres
    password: postgres

  flyway:
    enabled: true
    locations: classpath:db/migration

